### ISSUE TITLE
xcode 15  Stored properties cannot be marked

### ISSUE THREAD

**Issue by OkancanCosar** [relateddigital/visilabs-ios#55]
Hi, 👋 
when upgrade xcode to Version 15.0 (15A240d) getting error like 👇 

/ios/Pods/VisilabsIOS/Sources/Utilities/Checkbox.swift:103:6 
`
Stored properties cannot be marked unavailable with '@available'
`

is there anyone face it ?

**Comment by umutalparslan** [comment]
Hi @OkancanCosar,

This method has been deprecated. This issue has been fixed. Please update the SDK to the latest version.

**Comment by dogankablan** [comment]
Hi, I am using the Related-Digital package in my React Native project, and I'm encountering the same error with Xcode version 15.0. When I try to update the Visilabs SDK, I get an error. 

CocoaPods could not find compatible versions for pod "VisilabsIOS":
  In snapshot (Podfile.lock):
    VisilabsIOS (= 3.9.5, = 4.0.8)

  In Podfile:
    react-native-related-digital (from `../node_modules/react-native-related-digital`) was resolved to 0.1.13, which depends on
      VisilabsIOS (= 3.9.5)


What can I do to resolve this?

**Comment by OkancanCosar** [comment]
@dogankablan Downgrade xcode to 14.x.x works  for me. Because  react-native-related-digital depends VisilabsIOS.

**Comment by wirgvava** [comment]
same problem on Xcode 16.1, any solutions?
